export { OnBoardingSlide1, OnBoardingSlide2 } from "./onboarding";
export { default as MainPage } from "./main";
export { default as CreateEvaluationPage } from "./create-evaluations";
export { default as CreateEvaluationResultPage } from "./evaluation-create-result";
export { default as EvaluationPage } from "./evaluation";
export { default as EvaluationsPage } from "./evaluations";
export { default as ProfilePage } from "./profile";
export { default as MyEvaluationsPage } from "./my-evaluations";
export { default as CommentsFromCriterion } from "./comments-from-criterion";
export { default as EvaluationCriteria } from "./evaluation-criteria";
export { default as PassedEvaluations } from "./passed-evaluations";
export { default as PassedCriteriaByEvaluation } from "./passed-criteria-by-evaluation";
export { default as Constellations } from "./constellations";
export { default as MyConstellations } from "./my-constellations";
export { default as MascotStore } from "./mascot-store";
